### ISSUE TITLE
When converting the assembly, the axis and coordinate system of the part cannot be read

### ISSUE THREAD

**Issue by ycpss91255** [ros/solidworks_urdf_exporter#111]
Hello there!
When converting to URDF, the axis and coordinates of the part cannot system be read
<img width="519" alt="螢幕擷取畫面 2021-01-21 205402" src="https://user-images.githubusercontent.com/54975526/105354020-f09af100-5c2a-11eb-9e13-6f685617a576.png">

**Comment by brawner** [comment]
Hmm, strange indeed. Do you have a copy of a model that demonstrates this issue?

**Comment by ycpss91255** [comment]
[全向輪.zip](https://github.com/ros/solidworks_urdf_exporter/files/5853062/default.zip)
This is part of my model.
This problem can be reproduced by opening OWMR.SLDASM.
After testing, I found that it may be an assembly, and this error occurs when opening another assembly.

**Comment by brawner** [comment]
I think I realized what the issue here is. To prevent the tool from searching all the way down the tree of assemblies, it only looks for reference geometry in the top level and immediate children of the top level assembly. So it won't look more than one level down.

Try creating the geometries at the top level that are linked to the geometries at the lower levels. Do those show up?

**Comment by ycpss91255** [comment]
Yes, he will appear.
So if I need to let him search down, is there a way to adjust it?

**Comment by brawner** [comment]
Unfortunately, this is not possible currently.

The recommended solution is to organize the model such that there is one assembly per link. But looking at the names of your model, you have each roller in an omni wheel as a separate link? That might be overkill unless you need that sort of fidelity for simulation.

If you do need the whole omni wheel with separate links for each roller, then you might try exporting just the wheel as a urdf file. Edit that file to be a xacro macro (http://wiki.ros.org/xacro), then incorporate that back into the exported main assembly. 

I think this issue can be closed though. If you have further questions, please post them to answers.ros.org.

**Comment by ycpss91255** [comment]
thank you ,I will try to use xacro

**Comment by divserge** [comment]
Hi! Could you please point me to a place in the code, where this top-level cut-off happens? I'd like to improve the tool, by optionally allowing it to search deeper.

**Comment by divserge** [comment]
@brawner

**Comment by brawner** [comment]
For context, this greatly impacts large assembiles. This used to be the case, but was reduced to top level assemblies (#17). Please make a proposal about what this feature would look like and how it would be implemented. The amount of work to do this well is not trivial
