### ISSUE TITLE
Mesh export fails for STEP assemblies

### ISSUE THREAD

**Issue by ipa-hsd** [ros/solidworks_urdf_exporter#126]
**System Information**
1. SolidWorks version and service pack: 2021
2. Version of exporter: v1.6.1

**Bug**
The export of URDF is working fine. But the export of meshes only works in case of SOLIDWORKS assembly but not in case of STEP files (AP 214 specifically, I have not tried with other versions). The STL files are completely empty. 

Is this exporter meant only for SOLIDWORKS parts / assemblies?

**Comment by brawner** [comment]
Yes, this tool only exports STL files as STEP files are unrecognized by the ROS/Gazebo ecosystem.
