### ISSUE TITLE
solidworks_URDF

### ISSUE THREAD

**Issue by Ariharan09** [ros/solidworks_urdf_exporter#131]
**What versions of the installer have you tried?**

**Have you confirmed that installing by source is successful?**

**What version of SolidWorks and SP?**

**Comment by brawner** [comment]
Please reopen this issue using the update install template and fill in the requisite information. https://github.com/ros/solidworks_urdf_exporter/issues/new?assignees=&labels=Update+Installer&template=update-installer-request.md&title=
