### ISSUE TITLE
Problem with configuration manager

### ISSUE THREAD

**Issue by VijayR-Nair** [ros/solidworks_urdf_exporter#140]
When I tried to export a solidworks model of a four wheel mobile robot to URDF it keeps showing that there are some some problem with configuration manager "Reference sketch doesn't exist". In fact, I am new to ROS. Is that due to problem in the 3D model?

**Comment by brawner** [comment]
It's unclear from your description what is wrong with your SolidWorks model, but I would suggest deleting the urdf configuration and restarting the export.

**Comment by VijayR-Nair** [comment]
I have tried giving coordinate to all parts and it worked. Thanks for your response though!
