### ISSUE TITLE
Has this plugin stopped updating？

### ISSUE THREAD

**Issue by wxydejoy** [ros/solidworks_urdf_exporter#145]
Has this plugin stopped updating？
@brawner @mcevoyandy @davetcoleman @Extent421 @tonybaltovski @sachinkum0009 @708yamaguchi 

Please don't give up

**Comment by brawner** [comment]
Likely the binary just needs to be updated for the next release of SW. You can build it yourself according to the source directions on the wiki

**Comment by wxydejoy** [comment]
maybe we need package for ros2 ?

**Comment by gwitkowski2000** [comment]
@wxydejoy did you manage to get sw2urdf working with SolidWorks version 2022?

**Comment by wxydejoy** [comment]
@gwitkowski2000 So far, the plug-in can work normally with SolidWorks2022, but the version of the generated software package is only ROS1. You also need to manually modify the package.xml and CMakelist.txt in the software package.

**Comment by gwitkowski2000** [comment]
@wxydejoy it works indeed, perhaps i was looking in the wrong tab since it was in "Tools" instead of "File", where I was looking for it. I'm going to work with pyBullet, so unfortunately I don't have any experience with ROS2
