### ISSUE TITLE
sw2urdf window appears and then quickly disappears 

### ISSUE THREAD

**Issue by Femidis** [ros/solidworks_urdf_exporter#147]
**System Information**
1. Solidworks Premium 2020 SP1
2. Windows 10 64x
3. Visual Studio 2022 Community

I tried to install using pre-compile version 1.16.0, but when i try Export to URDF, plugin window blinks without any effect.
I try to install using compile way, but have some problems with install SolidWorks API SDK, all links outdated. When i finally found link and try to compile, plugin appears in Add-Ins, but i can't activate it. A tick in table Activated always disappers, and button Export in URDF not appears regardless of the model.

SolidWorks API i found in NuGet in Visual Studio, for installing i used instruction from Github

**Comment by shin0805** [comment]
When trying to use the URDF exporter with an sldprt file, I encountered a similar issue, but it didn't occur with an sldasm file : )

**Comment by weianweigan** [comment]
I forked this repos and fixed it. There is a release in [forked repos](https://github.com/weianweigan/Solidworks_urdf_exporter).

**Comment by brawner** [comment]
Would you be willing to make a PR?

**Comment by brawner** [comment]
What change actually addressed this issue? Perhaps you could just make a PR from that?

**Comment by weianweigan** [comment]
> What change actually addressed this issue? Perhaps you could just make a PR from that?

Ok
