### ISSUE TITLE
Doesnt work

### ISSUE THREAD

**Issue by Dorianproject** [ros/solidworks_urdf_exporter#151]
**What versions of the installer have you tried?**
download instaler.exe
**Have you confirmed that installing by source is successful?**
installation with exe was succesfull in SW i can clock on Export as URDF and nothing happends just for a mil second there appears a blank window and closes itself
**What version of SolidWorks and SP?**
Solidworks 2023 SP02.1

**Comment by brawner** [comment]
Duplicate
