### ISSUE TITLE
How to correct the mass, inertia matrix and centre of gravity manually? 

### ISSUE THREAD

**Issue by 15906185391** [ros/solidworks_urdf_exporter#164]
Hi,

I'm a student and I'm trying to export the urdf using the plugin. There are many parts that have an overridden mass in my robot model. I get wrong mass and moments of ineria and I am trying to correcting them manually.

Do I need to specify a specific coordinate system when I get the mass properties from SolidWorks?

![mass_pro](https://github.com/user-attachments/assets/f553af9c-5552-454f-9349-7b1bf0bc75e8)

I am not familar with them, could you please help me? @brawner 
Thank you very much!

**System Information**
1. SolidWorks version and service pack: SolidWorks 2024
2. Version of exporter 16.1

**Describe the bug**

**Comment by theanhnguyen3112** [comment]
give me the result of this problem, thank you
