### ISSUE TITLE
Exported STLs are in incorrect (Global?) Coordinate System

### ISSUE THREAD

**Issue by BenArtes** [ros/solidworks_urdf_exporter#87]
Solidworks 2019 SP3:

>Note: I'm a software developer who is working with Mechanical Engineers to get our models out of SW and into ROS so I don't have much experience with Solidworks, I'll summarize what I believe about Solidworks so that you know my thought process 

## Description

We're trying to export a robot model with multiple sub-assemblies and sub-sub-assemblies etc. The model is quite complex and due to some mating issues the automatic coordinate system / axis generation has been having trouble determining the correct coordinate systems / axes. In general we'd rather specify them manually anyway so that we have full control over placement etc, so we've decided to manually create coordinate systems / axes for control and to get around the automatic detection issues we've been having. 

The robot has multiple repeated parts so to simplify the creation of coordinate systems / axes we've added them to the sub-assemblies. This worked well and the URDF Tree Export Configuration window allowed us to select the specific sub-assembly coordinate system / axis we wanted to use for each link / joint.

Unfortunately when exported and viewed in RViz / Gazebo the model is not being assembled correctly. Importing all of the exported STLs into MeshLab the model is assembled correctly, so it appears that all of the STLs are being exported in the same (assumed global) coordinate system.

### Things I've tried:
* First looked at previous issues https://github.com/ros/solidworks_urdf_exporter/issues/73 and [Bug with function CreatePoint](https://bitbucket.org/brawner/sw2urdf/issues/36/bug-with-function-createpoint)
* Noticed that Solidworks 2019 API [SaveAs](http://help.solidworks.com/2019/English/api/sldworksapi/SolidWorks.Interop.sldworks~SolidWorks.Interop.sldworks.IModelDocExtension~SaveAs.html?verRedirect=1) was Obsoleted so updated to [SaveAs2](http://help.solidworks.com/2019/English/api/sldworksapi/SolidWorks.Interop.sldworks~SolidWorks.Interop.sldworks.IModelDocExtension~SaveAs2.html)
* Noticed `swFileSaveAsCoordinateSystem` has been obsoleted since [Solidworks 2017 API](http://help.solidworks.com/2017/English/api/swconst/FileSaveAsSTEPOptions.htm?verRedirect=1); not sure what to change
* Noticed that SaveSTL sets coordinate system from none unique `geo` name so duplicated all coordinate systems so that each was uniquely named (but still specified in sub-assembly).
>When reference geometry is created in the top-level its name is `name`, but when created in a sub-assembly the sub-assembly must be referenced in the name to specify it: `name<sub-assembly>`.
>
>The [SaveSTL](https://github.com/ros/solidworks_urdf_exporter/blob/master/SW2URDF/URDFExport/ExportHelper.cs#L310) function takes the coordinate system name and breaks it into the `geo` and component portions, then calls [`SetLinkSpecificSTLPreferences`](https://github.com/ros/solidworks_urdf_exporter/blob/master/SW2URDF/URDFExport/ExportHelper.cs#L491) so it can set the STLExport Coordinate System (via `swFileSaveAsCoordinateSystem`), but it only passes the `geo` portion of the coordinate system name.
* Tried calling `SetLinkSpecificSTLPreferences` with the full (`geo`+`<component>`) name.

None of the above resolved the issues.

Unfortunately, I can't share the Model; we could potentially try to recreate the issue with a test model, but I wanted to check if we were running into known behavior.

For now we're going to test a version of the model with all geometry specified in the Top Assembly.

**Comment by brawner** [comment]
Closing issue. Let me know if you have any related issues.
