### ISSUE TITLE
Location of previous releases

### ISSUE THREAD

**Issue by srsidd** [ros/solidworks_urdf_exporter#94]
I've been having issues outlined out in #73 and #87. I would like to try Version 1.2 of the plugin and see if that helps. Where can I get that from? (I'm not able to find that release here or on the ROS wiki)

**Comment by brawner** [comment]
An older version of the plugin likely won't fix this problem if you're using SolidWorks 2018 SP 1-4. You'll  need to upgrade to a newer version of SolidWorks.

This repo used to be hosted on https://bitbucket.org/brawner/sw2urdf but we pulled in all of its commits so you can also look at the git history of the [old installer](https://github.com/ros/solidworks_urdf_exporter/blob/11e0d70fe270b57d6d309d8c6071feae5a2d79bf/INSTALL/Output/sw2urdfSetup.exe)
