### ISSUE TITLE
Problems when V-REP importing URDF

### ISSUE THREAD

**Issue by Munrel** [ros/solidworks_urdf_exporter#95]
Hi, I have a problem to ask for help. When V-REP imports the urdf file export by SW2018, it has errors: "ERROR: file couldn't be opened." and "ERROR: there is no robot in the file." Could you give me some ideals? Thank you.

**Comment by brawner** [comment]
Are you able to launch the rviz example file? If you can attach the urdf package and solidworks assembly, it might help illustrate the issue.

**Comment by Munrel** [comment]
I will have a try, thank you for your help very much~

**Comment by brawner** [comment]
Closing this issue, due to age. Let me know if it needs to be reopened.

**Comment by charlotte-sy** [comment]
Have you guys got any updates? Same issue here. 

I have tried in rvis as well but there is no model is shown with no error
